### ISSUE TITLE
Practica #6: encuesta Abigail Coronel Santiago

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo_judith#2]
[PRACTICA DE ENCUESTAS (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo_judith/files/9930783/PRACTICA.DE.ENCUESTAS.1.pdf)

**Comment by Elisahadad** [comment]
30

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
